const dotenv = require('dotenv');
const path = require('path');
const connectDB = require('./config/db');
const City = require('./models/City');
const Attraction = require('./models/Attraction');

dotenv.config({ path: path.join(__dirname, '.env') });
connectDB();

const cities = [
  {
    cityName: 'Delhi',
    country: 'India',
    state: 'Delhi',
    location: 'National Capital Territory of Delhi',
    description: 'India\'s capital city, rich with historic monuments, bustling markets, museums, and cultural landmarks.',
    imageUrl: 'https://images.unsplash.com/photo-1544263166-836c1d7be1df?auto=format&fit=crop&w=1200&q=80',
    latitude: 28.6139,
    longitude: 77.2090,
  },
  {
    cityName: 'Mumbai',
    country: 'India',
    state: 'Maharashtra',
    location: 'West Coast of India',
    description: 'The financial capital of India, famous for the Arabian Sea waterfront, cinema culture, heritage sites, and iconic food spots.',
    imageUrl: 'https://images.unsplash.com/photo-1545606123-bb1b089c4d32?auto=format&fit=crop&w=1200&q=80',
    latitude: 19.0760,
    longitude: 72.8777,
  },
  {
    cityName: 'Jaipur',
    country: 'India',
    state: 'Rajasthan',
    location: 'Pink City, Rajasthan',
    description: 'The Pink City of India, known for royal forts, palaces, colorful bazaars, and traditional Rajasthani cuisine.',
    imageUrl: 'https://images.unsplash.com/photo-1523655594422-75a33d13f329?auto=format&fit=crop&w=1200&q=80',
    latitude: 26.9124,
    longitude: 75.7873,
  },
  {
    cityName: 'Agra',
    country: 'India',
    state: 'Uttar Pradesh',
    location: 'Yamuna River Basin',
    description: 'Home to the Taj Mahal and other Mughal-era wonders, Agra is one of India\'s most visited heritage cities.',
    imageUrl: 'https://images.unsplash.com/photo-1541456540-134f9ecda7d5?auto=format&fit=crop&w=1200&q=80',
    latitude: 27.1767,
    longitude: 78.0081,
  },
  {
    cityName: 'Bengaluru',
    country: 'India',
    state: 'Karnataka',
    location: 'Southern India',
    description: 'India\'s tech capital with beautiful gardens, palaces, modern cafes, and a lively food and culture scene.',
    imageUrl: 'https://images.unsplash.com/photo-1494503317504-17cfb12fc224?auto=format&fit=crop&w=1200&q=80',
    latitude: 12.9716,
    longitude: 77.5946,
  },
  {
    cityName: 'Kolkata',
    country: 'India',
    state: 'West Bengal',
    location: 'Eastern India',
    description: 'A cultural capital celebrated for colonial architecture, literature, riverfront landmarks, and legendary Bengali food.',
    imageUrl: 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?auto=format&fit=crop&w=1200&q=80',
    latitude: 22.5726,
    longitude: 88.3639,
  },
  {
    cityName: 'Hyderabad',
    country: 'India',
    state: 'Telangana',
    location: 'Deccan Plateau',
    description: 'A historic city blending grand Islamic architecture, technology hubs, lakeside sights, and world-famous biryani.',
    imageUrl: 'https://images.unsplash.com/photo-1599661046827-dacff0c0f09a?auto=format&fit=crop&w=1200&q=80',
    latitude: 17.3850,
    longitude: 78.4867,
  },
  {
    cityName: 'Vijayawada',
    country: 'India',
    state: 'Andhra Pradesh',
    location: 'Banks of the Krishna River',
    description: 'A vibrant Andhra city known for the Kanaka Durga Temple, riverfront views, bustling shopping areas, local food, and easy access to historic cave sites.',
    imageUrl: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1200&q=80',
    latitude: 16.5062,
    longitude: 80.6480,
  },
  {
    cityName: 'Chennai',
    country: 'India',
    state: 'Tamil Nadu',
    location: 'Coromandel Coast',
    description: 'A coastal cultural center known for temples, beaches, classical arts, and celebrated South Indian dining.',
    imageUrl: 'https://images.unsplash.com/photo-1566552881560-0be862a7c445?auto=format&fit=crop&w=1200&q=80',
    latitude: 13.0827,
    longitude: 80.2707,
  },
  {
    cityName: 'Varanasi',
    country: 'India',
    state: 'Uttar Pradesh',
    location: 'Banks of the Ganges',
    description: 'One of the world\'s oldest living cities, Varanasi is revered for ghats, temples, rituals, and spiritual heritage.',
    imageUrl: 'https://images.unsplash.com/photo-1561361058-c24cecae35ca?auto=format&fit=crop&w=1200&q=80',
    latitude: 25.3176,
    longitude: 82.9739,
  },
  {
    cityName: 'Udaipur',
    country: 'India',
    state: 'Rajasthan',
    location: 'Lake City of Rajasthan',
    description: 'Known as the City of Lakes, Udaipur is loved for palace views, romantic waterfronts, and heritage hospitality.',
    imageUrl: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=1200&q=80',
    latitude: 24.5854,
    longitude: 73.7125,
  },
];

const attractions = [
  {
    cityName: 'Delhi',
    name: 'Red Fort',
    description: 'A historic Mughal fortress and UNESCO World Heritage site in Old Delhi.',
    location: 'Netaji Subhash Marg, Lal Qila, Delhi 110006, India',
    category: 'Historical monument',
    imageUrl: 'https://images.unsplash.com/photo-1542131594-14f8f7558a5f?auto=format&fit=crop&w=1200&q=80',
    latitude: 28.6562,
    longitude: 77.2410,
    timings: '9:30 AM - 4:30 PM',
    ticketPrice: 'INR 35',
    bestTimeToVisit: 'October to March',
    travelTips: 'Visit early to avoid heavy crowds and combine it with Chandni Chowk exploration.',
  },
  {
    cityName: 'Delhi',
    name: 'India Gate',
    description: 'A war memorial and popular evening gathering spot in central Delhi.',
    location: 'Rajpath, India Gate, New Delhi, Delhi 110001, India',
    category: 'Landmark',
    imageUrl: 'https://images.unsplash.com/photo-1546549033-2c50e7c9fb29?auto=format&fit=crop&w=1200&q=80',
    latitude: 28.6129,
    longitude: 77.2295,
    timings: 'Open 24 hours',
    ticketPrice: 'Free',
    bestTimeToVisit: 'Evenings in winter',
    travelTips: 'Sunset is a great time to enjoy the lawns and nearby government district views.',
  },
  {
    cityName: 'Delhi',
    name: 'Karim\'s',
    description: 'Legendary Old Delhi restaurant known for Mughlai kebabs, korma, and rich North Indian flavors.',
    location: '16, Gali Kababian, Jama Masjid, Old Delhi, Delhi 110006, India',
    category: 'Restaurant',
    imageUrl: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=1200&q=80',
    latitude: 28.6507,
    longitude: 77.2334,
    timings: '12:00 PM - 11:30 PM',
    ticketPrice: 'Approx. INR 800 for two',
    bestTimeToVisit: 'Lunch or late evening',
    travelTips: 'Pair your visit with Jama Masjid and Old Delhi heritage walks.',
  },
  {
    cityName: 'Mumbai',
    name: 'Gateway of India',
    description: 'A historic arch monument overlooking the Arabian Sea in Mumbai.',
    location: 'Apollo Bandar, Colaba, Mumbai, Maharashtra 400001, India',
    category: 'Landmark',
    imageUrl: 'https://images.unsplash.com/photo-1534739823663-1c7b4777fa93?auto=format&fit=crop&w=1200&q=80',
    latitude: 18.9220,
    longitude: 72.8347,
    timings: 'Open 24 hours',
    ticketPrice: 'Free',
    bestTimeToVisit: 'Early morning or evening',
    travelTips: 'Take the nearby ferry view and combine it with a Colaba walk.',
  },
  {
    cityName: 'Mumbai',
    name: 'Marine Drive',
    description: 'A scenic seaside promenade known as the Queen\'s Necklace in South Mumbai.',
    location: 'Marine Drive, Mumbai, Maharashtra, India',
    category: 'Scenic spot',
    imageUrl: 'https://images.unsplash.com/photo-1508606572321-901ea4437074?auto=format&fit=crop&w=1200&q=80',
    latitude: 18.9430,
    longitude: 72.8238,
    timings: 'Open 24 hours',
    ticketPrice: 'Free',
    bestTimeToVisit: 'Sunset',
    travelTips: 'Visit during sunset for sea breeze and the best skyline views.',
  },
  {
    cityName: 'Mumbai',
    name: 'Leopold Cafe',
    description: 'One of Mumbai\'s most famous cafes, popular for its heritage charm, global menu, and Colaba atmosphere.',
    location: 'Shahid Bhagat Singh Road, Colaba Causeway, Mumbai, Maharashtra 400001, India',
    category: 'Restaurant',
    imageUrl: 'https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&w=1200&q=80',
    latitude: 18.9227,
    longitude: 72.8328,
    timings: '7:30 AM - 12:00 AM',
    ticketPrice: 'Approx. INR 1400 for two',
    bestTimeToVisit: 'Late afternoon or dinner',
    travelTips: 'Great stop after Gateway of India and Colaba Causeway shopping.',
  },
  {
    cityName: 'Jaipur',
    name: 'Hawa Mahal',
    description: 'The Palace of Winds famous for its distinctive pink sandstone facade.',
    location: 'Hawa Mahal Rd, Badi Chaupar, Jaipur, Rajasthan 302002, India',
    category: 'Palace',
    imageUrl: 'https://images.unsplash.com/photo-1496593813760-773d49ff8c38?auto=format&fit=crop&w=1200&q=80',
    latitude: 26.9239,
    longitude: 75.8267,
    timings: '9:00 AM - 4:30 PM',
    ticketPrice: 'INR 50',
    bestTimeToVisit: 'October to March',
    travelTips: 'Visit in the morning for softer light and fewer crowds.',
  },
  {
    cityName: 'Jaipur',
    name: 'Amber Fort',
    description: 'A majestic hilltop fort with ornate palaces and beautiful gardens.',
    location: 'Devisinghpura, Amer, Jaipur, Rajasthan 302028, India',
    category: 'Fort',
    imageUrl: 'https://images.unsplash.com/photo-1543489821-9e7ec0af6d1e?auto=format&fit=crop&w=1200&q=80',
    latitude: 26.9855,
    longitude: 75.8513,
    timings: '8:00 AM - 5:30 PM',
    ticketPrice: 'INR 100',
    bestTimeToVisit: 'Morning',
    travelTips: 'Wear comfortable shoes because there is a lot of walking uphill.',
  },
  {
    cityName: 'Jaipur',
    name: 'Laxmi Misthan Bhandar',
    description: 'A famous Jaipur restaurant and sweet shop loved for Rajasthani thali, kachori, and traditional sweets.',
    location: 'Johari Bazar Rd, Bapu Bazar, Jaipur, Rajasthan 302003, India',
    category: 'Restaurant',
    imageUrl: 'https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=1200&q=80',
    latitude: 26.9162,
    longitude: 75.8286,
    timings: '8:00 AM - 10:30 PM',
    ticketPrice: 'Approx. INR 600 for two',
    bestTimeToVisit: 'Breakfast or lunch',
    travelTips: 'Perfect stop while exploring the old city markets.',
  },
  {
    cityName: 'Agra',
    name: 'Taj Mahal',
    description: 'The iconic white marble mausoleum built by Mughal emperor Shah Jahan.',
    location: 'Dharmapuri, Forest Colony, Tajganj, Agra, Uttar Pradesh 282001, India',
    category: 'Monument',
    imageUrl: 'https://images.unsplash.com/photo-1505761671935-60b3a7427bad?auto=format&fit=crop&w=1200&q=80',
    latitude: 27.1751,
    longitude: 78.0421,
    timings: 'Sunrise - Sunset',
    ticketPrice: 'INR 50',
    bestTimeToVisit: 'Sunrise in winter',
    travelTips: 'Carry ID and arrive early because entry queues get long quickly.',
  },
  {
    cityName: 'Agra',
    name: 'Agra Fort',
    description: 'A historic red sandstone fort with palatial halls and sweeping views of the Taj Mahal.',
    location: 'Agra Fort, Agra, Uttar Pradesh 282003, India',
    category: 'Fort',
    imageUrl: 'https://images.unsplash.com/photo-1549880338-65ddcdfd017b?auto=format&fit=crop&w=1200&q=80',
    latitude: 27.1790,
    longitude: 78.0211,
    timings: '6:00 AM - 6:00 PM',
    ticketPrice: 'INR 50',
    bestTimeToVisit: 'Morning',
    travelTips: 'Combine it with Taj Mahal and Mehtab Bagh on the same day.',
  },
  {
    cityName: 'Agra',
    name: 'Pinch of Spice',
    description: 'A famous Agra restaurant popular for North Indian food and convenient dining after sightseeing.',
    location: '23, Fatehabad Rd, Basai, Tajganj, Agra, Uttar Pradesh 282001, India',
    category: 'Restaurant',
    imageUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=80',
    latitude: 27.1618,
    longitude: 78.0340,
    timings: '11:30 AM - 11:00 PM',
    ticketPrice: 'Approx. INR 1200 for two',
    bestTimeToVisit: 'Lunch or dinner',
    travelTips: 'A comfortable meal stop near the Taj tourism zone.',
  },
  {
    cityName: 'Bengaluru',
    name: 'Lalbagh Botanical Garden',
    description: 'A historic botanical garden famous for its glasshouse and seasonal flower shows.',
    location: 'Lalbagh Road, Bengaluru, Karnataka 560004, India',
    category: 'Garden',
    imageUrl: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80',
    latitude: 12.9507,
    longitude: 77.5848,
    timings: '6:00 AM - 7:00 PM',
    ticketPrice: 'INR 30',
    bestTimeToVisit: 'Morning',
    travelTips: 'The garden is especially beautiful during flower shows.',
  },
  {
    cityName: 'Bengaluru',
    name: 'Bangalore Palace',
    description: 'A Tudor-style palace with elegant interiors and sprawling grounds.',
    location: 'Vasanth Nagar, Bengaluru, Karnataka 560052, India',
    category: 'Palace',
    imageUrl: 'https://images.unsplash.com/photo-1511174511562-5f7f18b874f1?auto=format&fit=crop&w=1200&q=80',
    latitude: 12.9982,
    longitude: 77.5925,
    timings: '10:00 AM - 5:30 PM',
    ticketPrice: 'INR 240',
    bestTimeToVisit: 'Afternoon',
    travelTips: 'Carry extra time if you want to explore the palace grounds slowly.',
  },
  {
    cityName: 'Bengaluru',
    name: 'MTR',
    description: 'An iconic Bengaluru restaurant known for classic South Indian breakfast and traditional meals.',
    location: '14, Lalbagh Rd, Mavalli, Bengaluru, Karnataka 560004, India',
    category: 'Restaurant',
    imageUrl: '/uploads/images/attraction-mtr-bengaluru.png',
    latitude: 12.9551,
    longitude: 77.5854,
    timings: '6:30 AM - 11:00 AM, 12:30 PM - 8:30 PM',
    ticketPrice: 'Approx. INR 500 for two',
    bestTimeToVisit: 'Breakfast',
    travelTips: 'Arrive early because this place is busiest in the morning.',
  },
  {
    cityName: 'Kolkata',
    name: 'Victoria Memorial',
    description: 'A grand marble monument and museum dedicated to Queen Victoria.',
    location: 'Victoria Memorial Hall, Queens Way, Kolkata, West Bengal 700071, India',
    category: 'Monument',
    imageUrl: 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1200&q=80',
    latitude: 22.5448,
    longitude: 88.3426,
    timings: '10:00 AM - 5:00 PM',
    ticketPrice: 'INR 30',
    bestTimeToVisit: 'Winter afternoons',
    travelTips: 'The gardens are ideal for a slower heritage walk.',
  },
  {
    cityName: 'Kolkata',
    name: 'Howrah Bridge',
    description: 'A famous cantilever bridge spanning the Hooghly River and connecting Kolkata with Howrah.',
    location: 'Howrah Bridge, Kolkata, West Bengal, India',
    category: 'Landmark',
    imageUrl: 'https://images.unsplash.com/photo-1602921330641-a7b3ae776e7b?auto=format&fit=crop&w=1200&q=80',
    latitude: 22.5850,
    longitude: 88.3468,
    timings: 'Open 24 hours',
    ticketPrice: 'Free',
    bestTimeToVisit: 'Early morning or evening',
    travelTips: 'Visit nearby flower market for a fuller local experience.',
  },
  {
    cityName: 'Kolkata',
    name: 'Peter Cat',
    description: 'A legendary Park Street restaurant famous for chelo kebab and classic Kolkata dining.',
    location: '18A, Park St, Kolkata, West Bengal 700071, India',
    category: 'Restaurant',
    imageUrl: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=1200&q=80',
    latitude: 22.5526,
    longitude: 88.3526,
    timings: '12:00 PM - 11:00 PM',
    ticketPrice: 'Approx. INR 1400 for two',
    bestTimeToVisit: 'Dinner',
    travelTips: 'A good evening meal stop after Park Street exploration.',
  },
  {
    cityName: 'Hyderabad',
    name: 'Charminar',
    description: 'The signature 16th-century monument of Hyderabad and one of India\'s most recognized city landmarks.',
    location: 'Char Kaman, Ghansi Bazaar, Hyderabad, Telangana 500002, India',
    category: 'Landmark',
    imageUrl: '/uploads/images/attraction-charminar.png',
    latitude: 17.3616,
    longitude: 78.4747,
    timings: '9:30 AM - 5:30 PM',
    ticketPrice: 'INR 25',
    bestTimeToVisit: 'Evening',
    travelTips: 'Explore Laad Bazaar nearby for bangles and local shopping.',
  },
  {
    cityName: 'Hyderabad',
    name: 'Golconda Fort',
    description: 'A massive hill fort known for panoramic views, acoustic design, and royal history.',
    location: 'Khair Complex, Ibrahim Bagh, Hyderabad, Telangana 500008, India',
    category: 'Fort',
    imageUrl: '/uploads/images/attraction-golconda-fort.png',
    latitude: 17.3833,
    longitude: 78.4011,
    timings: '9:00 AM - 5:30 PM',
    ticketPrice: 'INR 25',
    bestTimeToVisit: 'Late afternoon',
    travelTips: 'Stay for sunset views if weather permits.',
  },
  {
    cityName: 'Hyderabad',
    name: 'Paradise Biryani',
    description: 'A famous Hyderabad restaurant closely associated with the city\'s iconic biryani culture.',
    location: 'SD Road, Secunderabad, Hyderabad, Telangana 500003, India',
    category: 'Restaurant',
    imageUrl: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=1200&q=80',
    latitude: 17.4417,
    longitude: 78.4983,
    timings: '11:00 AM - 11:00 PM',
    ticketPrice: 'Approx. INR 1000 for two',
    bestTimeToVisit: 'Lunch or dinner',
    travelTips: 'Expect a crowd during weekends and meal rush hours.',
  },
  {
    cityName: 'Hyderabad',
    name: 'Salar Jung Museum',
    description: 'One of India\'s most celebrated museums, known for its vast art, sculpture, clock, and decorative collections.',
    location: 'Darulshifa, Hyderabad, Telangana 500002, India',
    category: 'Museum',
    imageUrl: '/uploads/images/attraction-salar-jung-museum.png',
    latitude: 17.3713,
    longitude: 78.4804,
    timings: '10:00 AM - 5:00 PM',
    ticketPrice: 'INR 50',
    bestTimeToVisit: 'Morning',
    travelTips: 'Keep at least 2-3 hours because the museum complex is very large.',
  },
  {
    cityName: 'Hyderabad',
    name: 'Inorbit Mall',
    description: 'A popular shopping and entertainment mall in Hitec City with fashion stores, multiplex screens, and dining options.',
    location: 'Mindspace, Madhapur, Hyderabad, Telangana 500081, India',
    category: 'Mall',
    imageUrl: '/uploads/images/attraction-inorbit-mall-hyderabad.png',
    latitude: 17.4344,
    longitude: 78.3866,
    timings: '11:00 AM - 10:00 PM',
    ticketPrice: 'Free entry',
    bestTimeToVisit: 'Afternoon or evening',
    travelTips: 'Good option for indoor shopping and food when the weather is hot or rainy.',
  },
  {
    cityName: 'Hyderabad',
    name: 'Shah Ghouse',
    description: 'A favorite Hyderabad restaurant for biryani, grilled dishes, and late-night food runs.',
    location: 'Tolichowki, Hyderabad, Telangana 500008, India',
    category: 'Restaurant',
    imageUrl: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=1200&q=80',
    latitude: 17.4039,
    longitude: 78.4336,
    timings: '12:00 PM - 12:00 AM',
    ticketPrice: 'Approx. INR 900 for two',
    bestTimeToVisit: 'Dinner',
    travelTips: 'Expect a busy dinner rush, especially on weekends.',
  },
  {
    cityName: 'Vijayawada',
    name: 'Kanaka Durga Temple',
    description: 'A revered hilltop temple dedicated to Goddess Durga with sweeping views of the Krishna River and the city.',
    location: 'Indrakeeladri Hill, Vijayawada, Andhra Pradesh 520001, India',
    category: 'Temple',
    imageUrl: 'https://images.unsplash.com/photo-1624958723474-8f5a75ef0cbb?auto=format&fit=crop&w=1200&q=80',
    latitude: 16.5083,
    longitude: 80.6131,
    timings: '4:00 AM - 9:00 PM',
    ticketPrice: 'Free',
    bestTimeToVisit: 'Early morning',
    travelTips: 'Go early in the day to avoid long darshan queues and heat.',
  },
  {
    cityName: 'Vijayawada',
    name: 'Prakasam Barrage',
    description: 'An iconic river barrage and viewpoint that lights up beautifully in the evening along the Krishna waterfront.',
    location: 'Krishna River, Vijayawada, Andhra Pradesh, India',
    category: 'Landmark',
    imageUrl: 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=1200&q=80',
    latitude: 16.5067,
    longitude: 80.6161,
    timings: 'Open 24 hours',
    ticketPrice: 'Free',
    bestTimeToVisit: 'Evening',
    travelTips: 'Best visited around sunset when the riverfront gets cooler and more scenic.',
  },
  {
    cityName: 'Vijayawada',
    name: 'Undavalli Caves',
    description: 'Ancient rock-cut caves near Vijayawada known for their monolithic architecture and peaceful hill views.',
    location: 'Undavalli, Andhra Pradesh 522501, India',
    category: 'Historical site',
    imageUrl: '/uploads/images/attraction-undavalli-caves.png',
    latitude: 16.4957,
    longitude: 80.5748,
    timings: '9:00 AM - 6:00 PM',
    ticketPrice: 'INR 20',
    bestTimeToVisit: 'Morning or late afternoon',
    travelTips: 'Combine it with a short outing across the Krishna river for a half-day plan.',
  },
  {
    cityName: 'Vijayawada',
    name: 'PVP Square Mall',
    description: 'A central Vijayawada mall with shopping, movie screens, food outlets, and indoor entertainment.',
    location: 'MG Road, Labbipet, Vijayawada, Andhra Pradesh 520010, India',
    category: 'Mall',
    imageUrl: '/uploads/images/attraction-pvp-square-mall.png',
    latitude: 16.5069,
    longitude: 80.6486,
    timings: '10:00 AM - 10:00 PM',
    ticketPrice: 'Free entry',
    bestTimeToVisit: 'Afternoon or evening',
    travelTips: 'Useful for a relaxed indoor break after local sightseeing.',
  },
  {
    cityName: 'Vijayawada',
    name: 'Babai Hotel',
    description: 'A well-known Vijayawada restaurant loved for classic Andhra breakfasts, meals, and local comfort food.',
    location: 'Governor Peta, Vijayawada, Andhra Pradesh 520002, India',
    category: 'Restaurant',
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1200&q=80',
    latitude: 16.5185,
    longitude: 80.6282,
    timings: '7:00 AM - 10:30 PM',
    ticketPrice: 'Approx. INR 500 for two',
    bestTimeToVisit: 'Breakfast or lunch',
    travelTips: 'Great stop to try local Andhra flavors without overplanning.',
  },
  {
    cityName: 'Vijayawada',
    name: 'RR Durbar',
    description: 'A popular Vijayawada restaurant known for spicy Andhra meals, biryani, and family dining.',
    location: 'Benz Circle, Vijayawada, Andhra Pradesh 520010, India',
    category: 'Restaurant',
    imageUrl: 'https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&w=1200&q=80',
    latitude: 16.5016,
    longitude: 80.6466,
    timings: '12:00 PM - 11:00 PM',
    ticketPrice: 'Approx. INR 900 for two',
    bestTimeToVisit: 'Lunch or dinner',
    travelTips: 'A dependable stop for richer Andhra meals after city shopping or temple visits.',
  },
  {
    cityName: 'Chennai',
    name: 'Marina Beach',
    description: 'One of the longest urban beaches in the world and a defining public space of Chennai.',
    location: 'Marina Beach, Chennai, Tamil Nadu, India',
    category: 'Beach',
    imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
    latitude: 13.0500,
    longitude: 80.2824,
    timings: 'Open 24 hours',
    ticketPrice: 'Free',
    bestTimeToVisit: 'Early morning or evening',
    travelTips: 'Avoid peak afternoon heat and stay hydrated.',
  },
  {
    cityName: 'Chennai',
    name: 'Kapaleeshwarar Temple',
    description: 'A celebrated Dravidian temple in Mylapore known for colorful gopurams and cultural significance.',
    location: 'Mylapore, Chennai, Tamil Nadu 600004, India',
    category: 'Temple',
    imageUrl: 'https://images.unsplash.com/photo-1627894483216-2138af692e32?auto=format&fit=crop&w=1200&q=80',
    latitude: 13.0339,
    longitude: 80.2694,
    timings: '5:00 AM - 12:00 PM, 4:00 PM - 9:30 PM',
    ticketPrice: 'Free',
    bestTimeToVisit: 'Morning',
    travelTips: 'Dress modestly and keep some time for the Mylapore neighborhood walk.',
  },
  {
    cityName: 'Chennai',
    name: 'Murugan Idli Shop',
    description: 'A popular Chennai restaurant loved for idli, podi, dosa, and classic Tamil breakfast plates.',
    location: 'Besant Nagar, Chennai, Tamil Nadu, India',
    category: 'Restaurant',
    imageUrl: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=1200&q=80',
    latitude: 13.0004,
    longitude: 80.2660,
    timings: '6:30 AM - 10:30 PM',
    ticketPrice: 'Approx. INR 450 for two',
    bestTimeToVisit: 'Breakfast',
    travelTips: 'A great meal stop before or after the Besant Nagar beach area.',
  },
  {
    cityName: 'Varanasi',
    name: 'Kashi Vishwanath Temple',
    description: 'One of the most revered Hindu temples dedicated to Lord Shiva.',
    location: 'Lahori Tola, Varanasi, Uttar Pradesh 221001, India',
    category: 'Temple',
    imageUrl: 'https://images.unsplash.com/photo-1561361058-c24cecae35ca?auto=format&fit=crop&w=1200&q=80',
    latitude: 25.3109,
    longitude: 83.0107,
    timings: '3:00 AM - 11:00 PM',
    ticketPrice: 'Free',
    bestTimeToVisit: 'Early morning',
    travelTips: 'Plan around temple security and narrow-lane access.',
  },
  {
    cityName: 'Varanasi',
    name: 'Dashashwamedh Ghat',
    description: 'The most famous ghat in Varanasi, known for its evening Ganga Aarti ceremony.',
    location: 'Dashashwamedh Ghat Rd, Varanasi, Uttar Pradesh 221001, India',
    category: 'Cultural landmark',
    imageUrl: 'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=1200&q=80',
    latitude: 25.3063,
    longitude: 83.0105,
    timings: 'Open 24 hours',
    ticketPrice: 'Free',
    bestTimeToVisit: 'Evening for Ganga Aarti',
    travelTips: 'Arrive early if you want a better viewing spot for the ceremony.',
  },
  {
    cityName: 'Varanasi',
    name: 'Kashi Chat Bhandar',
    description: 'A well-known Varanasi food stop famous for local chaat and Banarasi street flavors.',
    location: 'Girjaghar Crossing, Varanasi, Uttar Pradesh 221001, India',
    category: 'Restaurant',
    imageUrl: 'https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=1200&q=80',
    latitude: 25.3179,
    longitude: 82.9918,
    timings: '10:00 AM - 10:00 PM',
    ticketPrice: 'Approx. INR 300 for two',
    bestTimeToVisit: 'Evening snack time',
    travelTips: 'Perfect for sampling local street-food culture after sightseeing.',
  },
  {
    cityName: 'Udaipur',
    name: 'City Palace',
    description: 'A grand palace complex overlooking Lake Pichola with museums, courtyards, and royal history.',
    location: 'Old City, Udaipur, Rajasthan 313001, India',
    category: 'Palace',
    imageUrl: 'https://images.unsplash.com/photo-1570168007204-dfb528c6958f?auto=format&fit=crop&w=1200&q=80',
    latitude: 24.5767,
    longitude: 73.6835,
    timings: '9:30 AM - 5:30 PM',
    ticketPrice: 'INR 300',
    bestTimeToVisit: 'Morning or late afternoon',
    travelTips: 'Combine with a Lake Pichola boat ride for the best experience.',
  },
  {
    cityName: 'Udaipur',
    name: 'Lake Pichola',
    description: 'A picturesque lake framed by palaces, ghats, hills, and some of Udaipur\'s best views.',
    location: 'Lake Pichola, Udaipur, Rajasthan, India',
    category: 'Scenic spot',
    imageUrl: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=1200&q=80',
    latitude: 24.5734,
    longitude: 73.6798,
    timings: 'Open 24 hours',
    ticketPrice: 'View free, boat rides extra',
    bestTimeToVisit: 'Sunset',
    travelTips: 'Sunset gives some of the best lake and palace photography.',
  },
  {
    cityName: 'Udaipur',
    name: 'Ambrai Restaurant',
    description: 'A famous Udaipur lakeside restaurant known for scenic dining with City Palace and Lake Pichola views.',
    location: 'Hanuman Ghat Marg, Outside Chand Pole, Udaipur, Rajasthan 313001, India',
    category: 'Restaurant',
    imageUrl: 'https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&w=1200&q=80',
    latitude: 24.5787,
    longitude: 73.6792,
    timings: '8:00 AM - 11:00 PM',
    ticketPrice: 'Approx. INR 1800 for two',
    bestTimeToVisit: 'Dinner',
    travelTips: 'Reserve in advance if you want prime lake-facing seating.',
  },
];

const importData = async () => {
  try {
    await City.deleteMany();
    await Attraction.deleteMany();

    const createdCities = await City.insertMany(cities);
    console.log('Cities seeded:', createdCities.length);

    const cityMap = createdCities.reduce((acc, city) => {
      acc[city.cityName] = city._id;
      return acc;
    }, {});

    const attractionDocs = attractions.map((item) => ({
      cityId: cityMap[item.cityName],
      name: item.name,
      description: item.description,
      location: item.location,
      category: item.category,
      imageUrl: item.imageUrl,
      latitude: item.latitude,
      longitude: item.longitude,
      timings: item.timings,
      ticketPrice: item.ticketPrice,
      bestTimeToVisit: item.bestTimeToVisit,
      travelTips: item.travelTips,
    }));

    const createdAttractions = await Attraction.insertMany(attractionDocs);
    console.log('Attractions seeded:', createdAttractions.length);
    process.exit();
  } catch (error) {
    console.error('Seeding error:', error);
    process.exit(1);
  }
};

importData();
